minecraft-server:
  ports:
    - "25565:25565"

  environment:
    EULA: "TRUE"
    WHITELIST: ourfunfamily,ourfunfamily2,ourfunfamily3
    MODE: creative
    MOTD: "Welcome to the O'Meara family and friends vanilla minecraft server. Vanilla comes from orchids!"
    MEMORY: "2G"
    TYPE: "FORGE"
    VERSION: 1.12.2
    OPS: ourfunfamily,ourfunfamily2,ourfunfamily3

  image: itzg/minecraft-server

  volumes:
    - /Users/bomeara/Dropbox/minecraft/mcworldedit_1:/data

  container_name: mcworldedit_1

  tty: true
  stdin_open: true
  restart: always
