minecraft-server:
  ports:
    - "25565:25565"

  environment:
    EULA: "TRUE"
    WHITELIST: ourfunfamily,ourfunfamily2,ourfunfamily3
    MODE: creative
    MOTD: "Welcome to the O'Meara family and friends vanilla minecraft server. Vanilla comes from orchids!"
    MEMORY: "2G"

  image: itzg/minecraft-server

  volumes:
    - /Users/gnomeara/Desktop/cheeseserver:/data

  container_name: mc_cheese

  tty: true
  stdin_open: true
  restart: always
