minecraft-server:
  ports:
    - "25565:25565"

  environment:
    EULA: "TRUE"
    WHITELIST: ourfunfamily,ourfunfamily2,ourfunfamily3
    MODE: creative

  image: itzg/minecraft-server

  volumes:
    - /Users/bomeara/Dropbox/minecraft/mcvanilla:/data

  container_name: mcvanilla

  tty: true
  stdin_open: true
  restart: always
